-- ============================================================
-- Migración 001
-- Creación de estructura para perfiles públicos de organizaciones
--
-- Actividad 2.5.2 - Migraciones y contratos de API para perfiles
--
-- Esta migración agrega las estructuras necesarias para el
-- portal público incorporado mediante la SC-01.
--
-- No modifica ni elimina información de las tablas existentes.
-- ============================================================

BEGIN;


-- ============================================================
-- 1. PLANTILLAS DE PERFIL
-- ============================================================

CREATE TABLE plantilla_perfil (
    id_plantilla SMALLINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    version VARCHAR(20) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT plantilla_perfil_pkey
        PRIMARY KEY (id_plantilla),

    CONSTRAINT plantilla_perfil_codigo_version_key
        UNIQUE (codigo, version)
);


-- ============================================================
-- 2. PERFIL PÚBLICO DE ORGANIZACIÓN
-- ============================================================

CREATE TABLE perfil_publico_organizacion (
    id_perfil_publico UUID NOT NULL DEFAULT uuid_generate_v4(),
    id_organizacion UUID NOT NULL,
    id_plantilla SMALLINT NOT NULL,

    slug VARCHAR(100),

    descripcion_publica TEXT,
    email_contacto_publico VARCHAR(255),
    telefono_contacto_publico VARCHAR(40),

    redes_sociales JSONB NOT NULL DEFAULT '{}'::jsonb,
    sitio_web_url TEXT,
    horario_atencion JSONB NOT NULL DEFAULT '{}'::jsonb,

    estado_publicacion VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',

    publicado_en TIMESTAMPTZ,
    retirado_en TIMESTAMPTZ,

    ocultado_por UUID,
    ocultado_en TIMESTAMPTZ,
    motivo_ocultamiento TEXT,
    estado_publicacion_anterior VARCHAR(20),

    creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT perfil_publico_organizacion_pkey
        PRIMARY KEY (id_perfil_publico),

    CONSTRAINT perfil_publico_organizacion_id_organizacion_key
        UNIQUE (id_organizacion),

    CONSTRAINT perfil_publico_organizacion_slug_key
        UNIQUE (slug),

    CONSTRAINT fk_perfil_publico_organizacion
        FOREIGN KEY (id_organizacion)
        REFERENCES organizacion (id_organizacion)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,

    CONSTRAINT fk_perfil_publico_plantilla
        FOREIGN KEY (id_plantilla)
        REFERENCES plantilla_perfil (id_plantilla)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,

    CONSTRAINT fk_perfil_publico_ocultado_por
        FOREIGN KEY (ocultado_por)
        REFERENCES usuario (id_usuario)
        ON DELETE SET NULL
        ON UPDATE NO ACTION,

    CONSTRAINT chk_perfil_publico_estado
        CHECK (
            estado_publicacion IN (
                'BORRADOR',
                'PUBLICADO',
                'NO_PUBLICADO',
                'OCULTO'
            )
        ),

    CONSTRAINT chk_perfil_publico_estado_anterior
        CHECK (
            estado_publicacion_anterior IS NULL
            OR estado_publicacion_anterior IN (
                'PUBLICADO',
                'NO_PUBLICADO'
            )
        ),

    CONSTRAINT chk_perfil_publico_slug_formato
        CHECK (
            slug IS NULL
            OR slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
        ),

    CONSTRAINT chk_perfil_publico_publicado_slug
        CHECK (
            estado_publicacion <> 'PUBLICADO'
            OR slug IS NOT NULL
        ),

    CONSTRAINT chk_perfil_publico_publicado_fecha
        CHECK (
            estado_publicacion <> 'PUBLICADO'
            OR publicado_en IS NOT NULL
        ),

    CONSTRAINT chk_perfil_publico_oculto
        CHECK (
            estado_publicacion <> 'OCULTO'
            OR (
                ocultado_en IS NOT NULL
                AND motivo_ocultamiento IS NOT NULL
                AND estado_publicacion_anterior IS NOT NULL
            )
        ),

    CONSTRAINT chk_perfil_publico_redes_sociales
        CHECK (
            jsonb_typeof(redes_sociales) = 'object'
        ),

    CONSTRAINT chk_perfil_publico_horario_atencion
        CHECK (
            jsonb_typeof(horario_atencion) = 'object'
        )
);


-- ============================================================
-- 3. IMÁGENES DEL PERFIL
-- ============================================================

CREATE TABLE imagen_perfil_organizacion (
    id_imagen UUID NOT NULL DEFAULT uuid_generate_v4(),
    id_perfil_publico UUID NOT NULL,

    url TEXT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    texto_alternativo VARCHAR(255),

    orden SMALLINT NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,

    mime_type VARCHAR(80),
    tamano_bytes BIGINT,

    creada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT imagen_perfil_organizacion_pkey
        PRIMARY KEY (id_imagen),

    CONSTRAINT fk_imagen_perfil_publico
        FOREIGN KEY (id_perfil_publico)
        REFERENCES perfil_publico_organizacion (id_perfil_publico)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,

    CONSTRAINT chk_imagen_perfil_orden
        CHECK (orden >= 0),

    CONSTRAINT chk_imagen_perfil_tamano
        CHECK (
            tamano_bytes IS NULL
            OR tamano_bytes >= 0
        )
);


-- ============================================================
-- 4. SECCIONES CONFIGURABLES DEL PERFIL
-- ============================================================

CREATE TABLE seccion_perfil_organizacion (
    id_seccion UUID NOT NULL DEFAULT uuid_generate_v4(),
    id_perfil_publico UUID NOT NULL,

    tipo_seccion VARCHAR(40) NOT NULL,
    titulo VARCHAR(180),
    contenido JSONB NOT NULL DEFAULT '{}'::jsonb,

    orden SMALLINT NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,

    actualizada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT seccion_perfil_organizacion_pkey
        PRIMARY KEY (id_seccion),

    CONSTRAINT fk_seccion_perfil_publico
        FOREIGN KEY (id_perfil_publico)
        REFERENCES perfil_publico_organizacion (id_perfil_publico)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,

    CONSTRAINT chk_seccion_perfil_orden
        CHECK (orden >= 0)
);


-- ============================================================
-- 5. ÍNDICES DE APOYO
-- ============================================================

CREATE INDEX idx_perfil_publico_id_plantilla
    ON perfil_publico_organizacion (id_plantilla);

CREATE INDEX idx_perfil_publico_estado
    ON perfil_publico_organizacion (estado_publicacion);

CREATE INDEX idx_imagen_perfil_publico_orden
    ON imagen_perfil_organizacion (id_perfil_publico, orden);

CREATE INDEX idx_seccion_perfil_publico_orden
    ON seccion_perfil_organizacion (id_perfil_publico, orden);


COMMIT;