BEGIN;

-- ============================================================
-- 1. CATEGORÍAS DE DONACIÓN
-- ============================================================

CREATE TABLE categoria_donacion (
    id_categoria_donacion SMALLINT
        GENERATED BY DEFAULT AS IDENTITY,

    nombre VARCHAR(120) NOT NULL,
    descripcion TEXT,

    CONSTRAINT categoria_donacion_pkey
        PRIMARY KEY (id_categoria_donacion),

    CONSTRAINT categoria_donacion_nombre_key
        UNIQUE (nombre)
);


-- ============================================================
-- 2. DONACIÓN
-- ============================================================

CREATE TABLE donacion (
    id_donacion UUID
        PRIMARY KEY
        DEFAULT uuid_generate_v4(),

    id_voluntario UUID NOT NULL,
    id_organizacion UUID NOT NULL,
    id_categoria_donacion SMALLINT NOT NULL,
    id_ubicacion UUID,

    descripcion TEXT NOT NULL,

    cantidad NUMERIC(10,2) NOT NULL,
    unidad VARCHAR(40) NOT NULL,

    condicion_bien VARCHAR(60) NOT NULL,
    disponible_desde DATE NOT NULL,

    imagen_url TEXT,

    estado VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDIENTE',

    idempotency_key UUID NOT NULL,

    creada_en TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),

    actualizada_en TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),


    CONSTRAINT fk_donacion_voluntario
        FOREIGN KEY (id_voluntario)
        REFERENCES perfil_voluntario(id_usuario),

    CONSTRAINT fk_donacion_organizacion
        FOREIGN KEY (id_organizacion)
        REFERENCES organizacion(id_organizacion),

    CONSTRAINT fk_donacion_categoria
        FOREIGN KEY (id_categoria_donacion)
        REFERENCES categoria_donacion(id_categoria_donacion),

    CONSTRAINT fk_donacion_ubicacion
        FOREIGN KEY (id_ubicacion)
        REFERENCES ubicacion(id_ubicacion),

    CONSTRAINT ck_donacion_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_donacion_estado
        CHECK (
            estado IN (
                'PENDIENTE',
                'ACEPTADA',
                'RECHAZADA',
                'COORDINADA',
                'RECIBIDA'
            )
        ),

    CONSTRAINT uq_donacion_idempotency
        UNIQUE (idempotency_key)
);


-- ============================================================
-- 3. HISTORIAL DE ESTADOS
-- ============================================================

CREATE TABLE historial_estado_donacion (
    id_historial UUID
        PRIMARY KEY
        DEFAULT uuid_generate_v4(),

    id_donacion UUID NOT NULL,

    cambiado_por UUID NOT NULL,

    estado VARCHAR(20) NOT NULL,

    observacion TEXT,

    cambiado_en TIMESTAMPTZ
        NOT NULL
        DEFAULT NOW(),


    CONSTRAINT fk_historial_donacion
        FOREIGN KEY (id_donacion)
        REFERENCES donacion(id_donacion)
        ON DELETE CASCADE,

    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (cambiado_por)
        REFERENCES usuario(id_usuario),

    CONSTRAINT ck_historial_estado_donacion
        CHECK (
            estado IN (
                'PENDIENTE',
                'ACEPTADA',
                'RECHAZADA',
                'COORDINADA',
                'RECIBIDA'
            )
        )
);


-- ============================================================
-- 4. ÍNDICES
-- ============================================================

CREATE INDEX idx_donacion_voluntario
    ON donacion(id_voluntario);

CREATE INDEX idx_donacion_organizacion
    ON donacion(id_organizacion);

CREATE INDEX idx_donacion_estado
    ON donacion(estado);

CREATE INDEX idx_donacion_categoria
    ON donacion(id_categoria_donacion);

CREATE INDEX idx_historial_donacion
    ON historial_estado_donacion(
        id_donacion,
        cambiado_en
    );

-- ============================================================
-- 5. CATÁLOGO INICIAL DE CATEGORÍAS
-- ============================================================

INSERT INTO categoria_donacion (
    nombre,
    descripcion
)
VALUES
    (
        'Alimentos',
        'Alimentos y productos destinados al consumo.'
    ),
    (
        'Ropa',
        'Prendas de vestir y elementos textiles.'
    ),
    (
        'Muebles',
        'Mobiliario y elementos de equipamiento.'
    ),
    (
        'Insumos',
        'Materiales e insumos de uso general.'
    )
ON CONFLICT (nombre) DO NOTHING;

COMMIT;